# --- CONFIGURACIÓN ---
$objetivo = $env:TARGET_DOMAIN
$tuNombre = "Auditoría Automática"
$puertos = @(21, 22, 25, 53, 80, 110, 143, 443, 3306, 3389)

# AJUSTE PARA GITHUB: Guardar en la carpeta actual
$reportePath = Join-Path $PSScriptRoot "Reporte_Seguridad.html"

# Configuración de red
try {
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
} catch {}
try {
    [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }
} catch {}

Write-Host "Iniciando escaneo de puertos sobre $objetivo..." -ForegroundColor Cyan

# 1. Inteligencia de Red
try {
    $ip = [System.Net.Dns]::GetHostAddresses($objetivo) | Select-Object -First 1 -ExpandProperty IPAddressToString
} catch {
    $ip = "No resuelta"
}

# 2. Escaneo de Puertos
$resultados = New-Object System.Collections.Generic.List[PSObject]

foreach ($p in $puertos) {
    $socket = New-Object System.Net.Sockets.TcpClient
    $res = [PSCustomObject]@{ Puerto = $p; Estado = "CERRADO"; Banner = "N/A"; Riesgo = "SEGURO"; Desc = "Puerto protegido." }

    try {
        $conn = $socket.BeginConnect($objetivo, $p, $null, $null)
        $wait = $conn.AsyncWaitHandle.WaitOne(1000, $false)

        if ($wait) {
            $socket.EndConnect($conn) | Out-Null
            $res.Estado = "ABIERTO"

            # Clasificación de Riesgo
            switch ($p) {
                21   { $res.Riesgo = "CRÍTICO"; $res.Desc = "FTP: Transferencia de archivos sin cifrar." }
                22   { $res.Riesgo = "BAJO"; $res.Desc = "SSH: Acceso seguro a la terminal." }
                25   { $res.Riesgo = "MEDIO"; $res.Desc = "SMTP: Envío de correo sin cifrar." }
                53   { $res.Riesgo = "MEDIO"; $res.Desc = "DNS: Consultas de nombres de dominio." }
                80   { $res.Riesgo = "ALTO"; $res.Desc = "HTTP: Tráfico web sin cifrar." }
                110  { $res.Riesgo = "ALTO"; $res.Desc = "POP3: Recepción de correo sin cifrar." }
                143  { $res.Riesgo = "ALTO"; $res.Desc = "IMAP: Recepción de correo sin cifrar." }
                443  { $res.Riesgo = "SEGURO"; $res.Desc = "HTTPS: Tráfico web cifrado." }
                3306 { $res.Riesgo = "CRÍTICO"; $res.Desc = "MySQL: Base de datos expuesta." }
                3389 { $res.Riesgo = "CRÍTICO"; $res.Desc = "RDP: Escritorio remoto expuesto." }
            }
            $res.Banner = "Servicio detectado"
        }
    } catch {
        # El estado por defecto es CERRADO, no se necesita acción
    } finally {
        if ($socket) { $socket.Close() }
    }

    $resultados.Add($res)
}

# 3. Generación de Reporte HTML
$riesgoColor = @{
    "SEGURO" = "#28a745"
    "BAJO"   = "#17a2b8"
    "MEDIO"  = "#ffc107"
    "ALTO"   = "#fd7e14"
    "CRÍTICO"= "#dc3545"
}

$html = @"
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reporte de Seguridad - $objetivo</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-900 text-white font-sans">

    <div class="container mx-auto p-8">

        <header class="text-center mb-10">
            <h1 class="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600">Security Audit Report</h1>
            <p class="text-gray-400 mt-2">Generated by $tuNombre on $(Get-Date -Format 'dd/MM/yyyy HH:mm:ss')</p>
        </header>

        <div class="max-w-4xl mx-auto bg-gray-800 rounded-2xl shadow-lg p-8 mb-10">
            <h2 class="text-2xl font-bold mb-4">Scan Summary</h2>
            <div class="grid grid-cols-2 gap-4 text-gray-300">
                <p><strong>Domain Analyzed:</strong></p><p>$objetivo</p>
                <p><strong>IP Address:</strong></p><p>$ip</p>
            </div>
        </div>

        <div class="max-w-4xl mx-auto bg-gray-800 rounded-2xl shadow-lg">
            <div class="overflow-x-auto">
                <table class="min-w-full text-sm text-left text-gray-300">
                    <thead class="text-xs text-white uppercase bg-gray-700">
                        <tr>
                            <th scope="col" class="px-6 py-3">Port</th>
                            <th scope="col" class="px-6 py-3">Status</th>
                            <th scope="col" class="px-6 py-3">Risk Level</th>
                            <th scope="col" class="px-6 py-3">Description</th>
                        </tr>
                    </thead>
                    <tbody>
                    $($resultados | ForEach-Object {
                        $statusClass = if ($_.Estado -eq 'ABIERTO') { 'text-red-400 font-bold' } else { 'text-green-400' }
                        $riesgoBg = switch ($_.Riesgo) {
                            "CRÍTICO" { "bg-red-600" }
                            "ALTO"    { "bg-orange-500" }
                            "MEDIO"   { "bg-yellow-500" }
                            "BAJO"    { "bg-blue-500" }
                            default   { "bg-green-500" }
                        }
                        "<tr class='bg-gray-800 border-b border-gray-700 hover:bg-gray-600'>" +
                        "<td class='px-6 py-4'>$($_.Puerto)</td>" +
                        "<td class='px-6 py-4 $statusClass'>$($_.Estado)</td>" +
                        "<td class='px-6 py-4'><span class='text-xs font-semibold inline-block py-1 px-2 uppercase rounded-full text-white $riesgoBg'>$($_.Riesgo)</span></td>" +
                        "<td class='px-6 py-4'>$($_.Desc)</td>" +
                        "</tr>"
                    })
                    </tbody>
                </table>
            </div>
        </div>

        <footer class="text-center mt-10 text-xs text-gray-500">
            Automated report.
        </footer>

    </div>

</body>
</html>
"@

$html | Out-File -FilePath $reportePath -Encoding UTF8
Write-Host "Reporte de seguridad guardado en: $reportePath" -ForegroundColor Green
